version: '3.7'

services:
  db:
    image: mysql
    restart: always
    volumes:
      - database:/var/lib/mysql
    environment:
      MYSQL_DATABASE: myprojectdb
      MYSQL_USER: myprojectdb
      MYSQL_PASSWORD: myprojectdb
      MYSQL_ROOT_PASSWORD: myprojectdb
    ports:
      - "3306:3306"
    expose: 
      - 3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
    depends_on:
      - db
    ports:
      - "8080:80"

  backend:
    build: .
    volumes:
      - .:/usr/share/backend
    ports:
      - "9000:9000"
      - "8089:8089"
    depends_on:
      - db
    tty: true

volumes:
  database: