# Generated by Django 3.1.6 on 2022-07-15 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_setting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='redirect_url',
            field=models.URLField(null=True),
        ),
    ]
