# Generated by Django 3.1.6 on 2022-07-15 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220715_1220'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Setting',
            new_name='PageSetting',
        ),
    ]
